# Generated by Django 5.2.8 on 2025-11-26 12:59

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_type', models.CharField(default='regular', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occasion', models.CharField(blank=True, choices=[('casual', 'Casual'), ('work', 'Work'), ('formal', 'Formal'), ('party', 'Party'), ('date', 'Date'), ('gym', 'Gym'), ('outdoor', 'Outdoor'), ('beach', 'Beach')], max_length=20, null=True)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Seasons')], max_length=20, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='outfits/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryType', models.CharField(blank=True, max_length=30)),
                ('SeasonType', models.CharField(blank=True)),
                ('item_image', models.ImageField(blank=True, upload_to='wardrobe/items/images')),
                ('category', models.CharField(blank=True, max_length=30)),
                ('season', models.CharField(blank=True, max_length=10)),
                ('brand', models.CharField(blank=True, max_length=30)),
                ('material', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('mid', 'Mid Layer'), ('outer', 'Outer Layer'), ('accessory', 'Accessory')], max_length=20)),
                ('z_index', models.IntegerField(default=0)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('size_width', models.FloatField(default=150)),
                ('size_height', models.FloatField(default=150)),
                ('rotation', models.FloatField(default=0)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.outfit')),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wardrobeitem')),
            ],
            options={
                'ordering': ['z_index'],
            },
        ),
    ]
