# Generated by Django 5.2.7 on 2025-10-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Innerwear', 'Innerwear'), ('Outerwear', 'Outerwear'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories')], default='', max_length=11)),
                ('season', models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='', max_length=10)),
                ('brand', models.CharField(default='', max_length=30)),
                ('material', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Authenticate',
        ),
    ]
