# Generated by Django 5.2.8 on 2025-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='CategoryType',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='SeasonType',
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Innerwear', 'Innerwear'), ('Outerwear', 'Outerwear'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Etc.', 'Etc.')], max_length=11),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('None', 'None')], max_length=10),
        ),
    ]
