# Generated by Django 5.2.8 on 2025-11-22 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occasion', models.CharField(blank=True, choices=[('casual', 'Casual'), ('work', 'Work'), ('formal', 'Formal'), ('party', 'Party'), ('date', 'Date'), ('gym', 'Gym'), ('outdoor', 'Outdoor'), ('beach', 'Beach')], max_length=20, null=True)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Seasons')], max_length=20, null=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='outfits/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('mid', 'Mid Layer'), ('outer', 'Outer Layer'), ('accessory', 'Accessory')], max_length=20)),
                ('z_index', models.IntegerField(default=0)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('size_width', models.FloatField(default=150)),
                ('size_height', models.FloatField(default=150)),
                ('rotation', models.FloatField(default=0)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wardrobeitem')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.outfit')),
            ],
            options={
                'ordering': ['z_index'],
            },
        ),
    ]
