# Generated by Django 5.2.8 on 2025-12-01 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_wardrobeitem_categorytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
