# Generated by Django 5.2.7 on 2025-10-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wardrobeitem_delete_authenticate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='brand',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Innerwear', 'Innerwear'), ('Outerwear', 'Outerwear'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Etc.', 'Etc.')], max_length=11),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='http://127.0.0.1:8000/wardrobe/items/images'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='material',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('None', 'None')], max_length=10),
        ),
    ]
