# Generated by Django 5.2.8 on 2025-11-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_wardrobeitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
