# Generated by Django 5.2.7 on 2025-10-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_wardrobeitem_brand_alter_wardrobeitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
