# Generated by Django 5.2.8 on 2025-11-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_wardrobeitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Tops', 'Tops'), ('Bottoms', 'Bottoms'), ('Innerwear', 'Innerwear'), ('Outerwear', 'Outerwear'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('One-Pieces', 'One-Pieces'), ('Etc.', 'Etc.')], max_length=11),
        ),
    ]
