# Generated by Django 5.2.7 on 2025-10-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_wardrobeitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
