# Generated by Django 5.2.7 on 2025-10-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_wardrobeitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='wardrobe/items/images'),
        ),
    ]
