# Generated by Django 5.2.8 on 2025-12-02 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_wardrobeitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wardrobeitem",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "weather",
                    models.CharField(
                        choices=[
                            ("sunny", "Sunny"),
                            ("cloudy", "Cloudy"),
                            ("rainy", "Rainy"),
                            ("snowy", "Snowy"),
                            ("hot", "Hot"),
                            ("cold", "Cold"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("professional", "Professional"),
                            ("formal", "Formal"),
                            ("party", "Party"),
                            ("date", "Date"),
                            ("gym", "Gym"),
                            ("outdoor", "Outdoor"),
                            ("beach", "Beach"),
                        ],
                        max_length=20,
                    ),
                ),
                ("temperature", models.IntegerField(blank=True, null=True)),
                ("compatibility_score", models.FloatField(default=0.0)),
                ("explanation", models.TextField()),
                (
                    "recommended_items",
                    models.ManyToManyField(
                        related_name="recommendations", to="api.wardrobeitem"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
