# Generated by Django 5.2.8 on 2025-12-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_wardrobeitem_user_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outfit",
            name="scheduled_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
