# Generated by Django 5.2.8 on 2025-12-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_outfit_is_favorite_outfit_scheduled_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wardrobeitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Tops", "Tops"),
                    ("Bottoms", "Bottoms"),
                    ("Mid Layer", "Mid Layer"),
                    ("Outer Layer", "Outer Layer"),
                    ("Accessory", "Accessory"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
